[project]
name = "hello-qiskit"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "qiskit[visualization]>=2.1.2",
    "qiskit-ibm-runtime>=0.41.1",
]
